import { GridColDef } from '@mui/x-data-grid';

export type TypeUserMng = {
  uid: string,
  userId?: string,
  email?: string,
  nickname?: string,
  picture?: string,
  role?: string,
  isLocked?: string,
  isDormant?: string,
  passwordMdate?: string,
  cdate?: string,
  mdate?: string,
  site?: string,
  snsId?: string,
  cdate_2?: string,
  mdate_2?: string,
  email_3?: string,
  cdate_3?: string,
  mdate_3?: string,
};

export const ColUserMng: GridColDef[] = [
  {field: 'uid', headerName: 'uid'},
  {field: 'userId', headerName: 'userId'},
  {field: 'email', headerName: 'email'},
  {field: 'nickname', headerName: '닉네임'},
  {field: 'picture', headerName: '이미지'},
  {field: 'role', headerName: '권한'},
  {field: 'isLocked', headerName: 'locked'},
  {field: 'isDormant', headerName: 'dormant'},
  {field: 'passwordMdate', headerName: '패스워드 변경일자'},
  {field: 'cdate', headerName: 'user 등록일자'},
  {field: 'mdate', headerName: 'user 수정일자'},
  {field: 'site', headerName: 'site'},
  {field: 'snsId', headerName: 'SNS ID'},
  {field: 'cdate_2', headerName: 'SNS연동 등록일자'},
  {field: 'mdate_2', headerName: 'SNS연동 수정일자'},
  {field: 'email_3', headerName: 'SNS등록 email'},
  {field: 'cdate_3', headerName: 'SNS 로그인 등록일자'},
  {field: 'mdate_3', headerName: 'SNS 로그인 수정일자'},
];